# Site settings
course_code: ELL409 
course_name: "MACHINE INTELLIGENCE & LEARNING"
course_description: "This is an introductory course on Machine Learning (ML) that is offered to undergraduate students. The contents are designed to cover both theoretical and practical aspects of several well-established ML techniques. The assignments will contain theory and programming questions that help strengthen the theoretical foundations as well as learn how to engineer ML solutions to work on simulated and publicly available real datasets. The project(s) will require students to develop a complete Machine Learning solution requiring preprocessing, design of the classifier/regressor, training and validation, testing and evaluation with quantitative performance comparisons."
course_semester: "Sem-I, 2024"

baseurl: "/ELL409-2401" # the subpath of your site, e.g. /blog/
url: "http://lcs2-iitd.github.io/" # the base hostname & protocol for your site

schoolname: "IIT Delhi"
schoolurl: "https://www.lcs2.in"
twitter_username: lcs2lab 

address: |
    Laboratory for Computational Social Systems (LCS2)
    Indian Institute of Technology Delhi
    Hauz Khas, New Delhi - 110016, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-FYNEGWXPQZ

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
