# Site settings
course_code: ELL884
course_name: "DEEP LEARNING FOR NATURAL LANGUAGE PROCESSING"
course_description: "Natural Language Processing (NLP) is the art of teaching a computer how to understand (human) language. It is a type of AI technology that allows an automated system to understand human needs through natural language. Anything that deals with human languages (texts or speeches), such as web search, recommendation systems, chatbots, language translation, and social media, comes under the realm of NLP. Due to the success of deep learning, in the last decade, NLP has witnessed a massive change in how a computer perceives a language. The blend of classical NLP with neural networks has shown promising performance in almost every application. This crash course intends to provide a holistic view of modern NLP techniques. It will start with two introductory sections -- basics of NLP and introduction to deep learning, following which it will broadly focus on deep learning methods for NLP. The course is designed for senior undergraduate and graduate students of any discipline, who carry introductory knowledge of machine learning and a strong Python programming skill. The students are not expected to carry any prior knowledge of NLP at the start of the course. We will cover foundational architectures, different training protocols, and several downstream NLP tasks. The course will include programming assignments (in Python), quizzes, course projects, research paper reading, and two written exams (midterm and major)."
course_semester: "Sem-II, 2024-25"

baseurl: "/ELL84-2402" # the subpath of your site, e.g. /blog/
url: "http://lcs2-iitd.github.io/" # the base hostname & protocol for your site

schoolname: "IIT Delhi"
schoolurl: "https://www.lcs2.in"
twitter_username: lcs2lab 

address: |
    Laboratory for Computational Social Systems (LCS2)
    Indian Institute of Technology Delhi
    Hauz Khas, New Delhi - 110016, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-FYNEGWXPQZ

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
